language: go

go:
  - 1.8.x

install:
  - go get github.com/GAumala/mpd-http-proxy
  - go get github.com/stretchr/testify/assert

script:
  - cd $GOPATH/src/github.com/GAumala/mpd-http-proxy/
  - go build main.go
  - cd mpd-cli
  - go build main.go
  - cd ../mpd
  - go test -cover
